# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [7]:
# Your code here
import numpy as np

def generate_random_matrix(m,n, n_matrix = 1):
    
    matricies = []
    for k in range(n_matrix):
        matrix = np.zeros((m,n))

        for i in range(m):
            for j in range(n):
                matrix[i,j] = np.random.randint(1, 11)
                
        matricies.append(matrix)
        
    if n_matrix == 1:
        return matrix
    else:
        return matricies

In [9]:
A,B,C = generate_random_matrix(4,4, 3)
A @ (B + C) == A @ B + A @ C

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [10]:
# Your code here 
A @ (B @ C) == (A @ B) @ C

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [18]:
# Your code here 

A @ B == B @ A

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [15]:
# Your code here 
A.T @ B == B.T * A

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [39]:
x, y = np.random.randint(1, 11, 4), np.random.randint(1, 11, 4)
x, y


(array([3, 3, 4, 4]), array([6, 5, 2, 1]))

In [40]:
left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
left == right

True

In [33]:
left = np.transpose(x[0]).dot(y[0])
right = np.transpose(y[0]).dot(x[0])
left == right

True

In [19]:
x = np.array([[2], [6], [7]])
y = np.array([[3], [5], [9]])

left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
left == right

array([[ True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [16]:
# Your code here 
(A @ B).T == B.T @ A.T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
# can we just use randint to generate a matrix?
D = np.random.randint(1, 11, (3,3))
D

array([[1, 9, 8],
       [9, 9, 8],
       [8, 4, 9]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 